### ISSUE TITLE
ViewPager in popoverview

### ISSUE THREAD

**Issue by aperritano** [lupidan/PopoverView#3]
is this possible - ViewPager with multiple fragments within the popoverview? pretty much this example in a popover, nothing more complex than this.

http://developer.android.com/training/animation/screen-slide.html

I have tried to take the example and add to the popoverview. unsuccessful. still a bit new to android. how would i go about doing this? 

this would be a great addition to the popoverview

thanks and keep up the good work :)

**Comment by lupidan** [comment]
IT IS possible, and I have done it for an app :)
It's not really an addition, since you can put almost ANY view inside the PopoverView. I used to put a ViewPager with a ViewPageIndicator from Jake Wharton https://github.com/JakeWharton/Android-ViewPagerIndicator/

I don't know about your code, but remember that, for PopoverView to work, your root view needs to be a RelativeLayout or similar, since the popover needs to appear on top of any view in a relative position. If you need to use a Linear Layout in your app, you should contain it in the root Relative Layout with FILL_PARENT Layout Params.

-> Relative Layout (rootLayout)
 _______|------> Linear Layout
_________________|--------> Your app content

And then, to show a popover, do it from the rootLayout.

Please, go to the README to see how to instantiate the Popover View and show it. Also, please check the interface XMLs in the example, and you will see the container is a RelativeLayout :)

Hope that helps!

**Comment by aperritano** [comment]
viewPager+ViewPageIndicator+popoverview is exactly what i am looking for. do you have a sample I could look at?  Your suggestion cleared up some confusion.  How to instantiate the view pager on the fly and pass it to the popover view in a listener?  For instance i have this listener:

or is this a bad place to do it?

```
button.setOnClickListener(new View.OnClickListener() {

        @Override
        public void onClick(View v) {
            Log.i("onClickButton", "test button");

            //make view pager here?

            PopoverView popoverView = new PopoverView(TheoryFragment.this.getActivity(),R.layout.activity_screen_slide);
            popoverView.setContentSizeForViewInPopover(new Point(500, 340));        
            popoverView.showPopoverFromRectInViewGroup((ViewGroup) mainLayoutView.getParent(), PopoverView.getFrameForView(v), PopoverView.PopoverArrowDirectionAny, true);

        }
    });
```

thanks!

**Comment by lupidan** [comment]
Here is a working example I made in a few minutes, it was nice remembering how to use the ViewPager. To see it working, just replace the onClick method with this one in the main example.
What I am just doing is create a ViewPager with an adapter, it has 4 copies of the same layout and you can scroll trough them horizontally.

```
@Override
public void onClick(View v) {
    //get root layout
    RelativeLayout rootView = (RelativeLayout)findViewById(R.id.rootLayout);

    ViewPager pager = new ViewPager(this);
    pager.setAdapter(new PagerAdapter() {

        @Override
        public boolean isViewFromObject(View arg0, Object arg1) {
            return arg0 == arg1;
        }

        @Override
        public int getCount() {
            return 4;
        }

        /* (non-Javadoc)
         * @see android.support.v4.view.PagerAdapter#instantiateItem(android.view.ViewGroup, int)
         */
        @Override
        public Object instantiateItem(ViewGroup container, int position) {
            View view = View.inflate(container.getContext(), R.layout.popover_showed_view, null);
            container.addView(view, LayoutParams.FILL_PARENT, LayoutParams.FILL_PARENT);
            return view;
        }

        /* (non-Javadoc)
         * @see android.support.v4.view.PagerAdapter#destroyItem(android.view.ViewGroup, int, java.lang.Object)
         */
        @Override
        public void destroyItem(ViewGroup container, int position, Object object) {
            container.removeView((View)object);
        }



    });

    //PopoverView popoverView = new PopoverView(this, R.layout.popover_showed_view);
    PopoverView popoverView = new PopoverView(this, pager);
    //You can put whatever size here
    popoverView.setContentSizeForViewInPopover(new Point(400, 400));
    popoverView.setDelegate(this);
    popoverView.showPopoverFromRectInViewGroup(rootView, PopoverView.getFrameForView(v), PopoverView.PopoverArrowDirectionAny, true);

}
```

I hope that helps :)

**Comment by aperritano** [comment]
This totally works. Popoverview with a view pager looks sweet. 

thanks
